### ISSUE TITLE
Images from Insta360 Evo not supported

### ISSUE THREAD

**Issue by azw413** [steren/stereo-img#48]
![sample](https://github.com/steren/stereo-img/assets/44088111/ce3b8f1a-154b-4d5f-a03d-d639d332943b)

When using this image as a sample, I get an error :- 

```
stereo-img.js:204 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'width')
    at StereoImg.createEye (stereo-img.js:204:21)
    at StereoImg.initialize3DScene (stereo-img.js:311:18)
    at async StereoImg.parseImageAndInitialize3DScene (stereo-img.js:320:7)
    at async StereoImg.init (stereo-img.js:366:7)
```

You can keep this image as an example for your project, thanks

**Comment by steren** [comment]
Thanks for the bug report. 

I was able to load this image successfully at https://stereo-img.steren.fr

While it loads fine in the viewer, the field of view isn't automatically detected as a 180. I will see what I can do to improve this. 

Can you share the exact steps you are using? (component attributes)

**Comment by azw413** [comment]
That's interesting, I also uploaded to your site and it displayed without issue. I cloned the project and copied the js client side libraries in `lib`, `parsers`, `vendor` and `stereo-img.js` to the docroot and then used this as the template :- 
```
<html>
<head>

    <!-- Polyfill for WebXR -->
    <script src='https://cdn.jsdelivr.net/npm/webxr-polyfill@latest/build/webxr-polyfill.js'></script>
    <script>
        window.polyfill = new WebXRPolyfill();
    </script>

    <script type="module" src="stereo-img.js"></script>
</head>
<body>
<stereo-img src="media/sample.jpg" type="vr"></stereo-img>
</body>
</html>
```

So basically copying your example. I don't have an npm backend and instead using a rust backend so maybe I've missed some crucial step. I'm assuming that all the logic is client side, perhaps I'm mistaken and there's some processing on the server? 

Thanks.

**Comment by steren** [comment]
Thanks, can you replace `type=vr` with `type=left-right` ? Or remove the attribute entirely.

I'll make sure the component doesn't crash when the VR180 type cannot find metadata it is looking for

**Comment by azw413** [comment]
Thanks for the help, that worked perfectly :- 
```
<stereo-img src="media/sample.jpg" angle="180" wiggle="false"></stereo-img>
```

**Comment by azw413** [comment]
I've tried a few other SBS 3D images and, I get the same result: views fine in non-VR mode but the 'Enter VR' mode doesn't seem to enter the WebXR mode and instead just displays a binocular stereo view with image data only in the left eye, which does respond to headset movement but the right eye is empty and it just doesn't enter the WebXR view. Here's an example from a non VR-180 3d camera.
![bloggie](https://github.com/steren/stereo-img/assets/44088111/81502087-329a-4e85-b3ec-462b219a5c49)

**Comment by steren** [comment]
This is a different issue than the Insta360.
Can you create a new issue?

**Comment by steren** [comment]
Added image to example folder in https://github.com/steren/stereo-img/commit/ff907649cb004e99180f7f862308e3d15b152e2b

**Comment by steren** [comment]
using https://mutiny.cz/exifr/, I wasn't able to see any focal length information in the example image.

So we'll need to hardcode using 180deg when  `"Model": "insta360 evo"`

**Comment by steren** [comment]
Hardcoded in https://github.com/steren/stereo-img/commit/f4025b27d885722282f7fee1a29b74131780833d

Added as example in https://github.com/steren/stereo-img/commit/89890dcf5c2f88fa7ab0851f875f28ff3f0b2ba4
